<?php

namespace app\models;

use Yii;
use app\components\helpers\RedisHelper;

/**
 * This is the model class for table "{{%article_comment}}".
 *
 * @property integer $id
 * @property integer $article_id
 * @property integer $comment_id
 * @property integer $user_id
 * @property integer $answer_user_id
 * @property integer $praise_num
 * @property string $content
 * @property integer $created_at
 */
class ArticleComment extends \yii\db\ActiveRecord
{
    public $praiseKey= 'article.comment.praise.user.';
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%article_comment}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['article_id', 'comment_id', 'user_id', 'answer_user_id', 'created_at'], 'integer'],
            [['content'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'article_id' => '文章ID',
            'comment_id' => '回复评论ID',
            'user_id' => '用户ID',
            'answer_user_id' => '回复用户ID',
            'content' => '评论内容',
            'created_at' => '创建时间',
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        $this->user_id = Yii::$app->user->id;
        $this->created_at = time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * 用户关系
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id'])->select(['id', 'nickname', 'avatar']);
    }

    /**
     * 获取用户评论
     * @param $id
     * @return array|\yii\db\ActiveRecord[]
     */
    public function getComments($id)
    {
        $comments = self::find()
            ->innerJoinWith(['user'])
            ->where(['article_id' => $id])
            ->indexBy('id')
            ->asArray()
            ->all();

        $userId = !Yii::$app->user->isGuest ? Yii::$app->user->id : 0;
        foreach ($comments as $comment){
            if($comment['comment_id']){
                $comments[$comment['comment_id']]['child'][] = $comment;
                $comments[$comment['comment_id']]['user'][$comment['user']['id']] = $comment['user'];
                unset($comments[$comment['id']]);
            }else{
                $comments[$comment['id']]['praise_num'] = RedisHelper::setCard($this->praiseKey . $comment['id']);
                $comments[$comment['id']]['is_praise'] = $userId ? RedisHelper::setIsMember($this->praiseKey . $comment['id'], $userId) : false;
            }
        }

        return $comments;
    }
}
